version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: "FABRIC"
      WORLD: "/worlds/basic/world.zip"
      MODS_FILE: "/extras/mods.txt"
      # FORCE_WORLD_COPY: true
      # ETRA_ARGS='--word-dir ./'
    ports:
      - "3000:25565"
    volumes:
      # - data:/data
      # attach a directory relative to the directory containing this compose file
      - ./worlds:/worlds:ro
      - ./extras:/extras:ro
      - ./minecraft-data:/data

    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}